sudo: required
dist: trusty
language: node_js
node_js:
- 4
cache: yarn
cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
before_script:
  - lerna bootstrap
script:
  - lerna run test
