sudo: required
dist: trusty
language: node_js
node_js:
- 4
cache:
  directories:
  - node_modules
before_install:
  - brew update
  - brew outdated yarn || brew upgrade yarn
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd packages/runtime
  - npm install
script:
  - yarn run test
